name: genshin
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - google-auth-oauthlib=0.4.6
    - google-spreadsheet=0.0.6
    - numpy=1.22.2
    - pandas=1.4.1
    - plotly=5.6.0
    - jupyterlab=3.2.9
    - gspread=5.1.1